# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache: pip
# build matrix: different python and pandoc versions
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
  # pypy (version info from [Changelogs — PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"  # PyPy2.7 5.3.1 (CPython 2.7 compatible)
  - "pypy3" # PyPy3 2.4.0 (CPython 3.2 compatible)
matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "nightly"
    # - python: "pypy3"
  fast_finish: true
# install dependencies
install:
  # latest pip dropped support for py3.2, which is the version of python in pypy3
  - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then pip install -U pip; fi
  - pip install -e .[test]
before_script:
  # pasteurize for py2 only, except setup.py & pantable/version.py
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then
      mv setup.py setup.py.temp
      pasteurize -wnj 4 .
      mv setup.py.temp setup.py
    fi
# command to run tests
script:
  - make -j4 test
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then coveralls; else printf "skip coveralls"; fi
before_deploy:
  # build unpasteurized python3 wheel
  - python3 setup.py bdist_wheel
  # pasteurize except setup.py & pantable/version.py
  - |
    mv setup.py setup.py.temp
    pasteurize -wnj 4 .
    mv setup.py.temp setup.py
  # prepare wheel for py2
  - pip2 install wheel
  - python2 setup.py bdist_wheel
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  # do not add bdist_wheel here, since it is done above
  distributions: "sdist"
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
env:
  global:
    secure: t5r8ZHBc3ZawMahCW3gWCu7AxvzYYUT/FpiS7Yqt4aasrRqY+G/fXecx+DgmYADxuxLNeW9hg8zfJDAPGT4nDNAnaFq28339lFdiiqFbiov/mmrc075YVyJP5QU24mTgolfdmGr0dqfRfTjVQqNwkDtHfyJKV/9PH1HNNFTRqg4hFYpodEtIzSCTRfWncgkfbhz8mYtLQNO7ZhixjeyPB2XdY56ylTj6LFY56ij2pnj0ZvDYj3/LtaqcZjreAXoVmAONZizc0qdHegpi3fReYtQ5BeZYQb7xsmUCcUjAVMF9ZvVoWoDawO/zG8w6qCBLYv9HGVGdwmv+8rQShZ17HVO/mQ7Djm19QkI3Cd1tJnwORWKNbWYKVm7wUPkH0f+/YLykzqeATW8wnhIsleQ4DH1Z1zwIsrXBFQd0YKH4NANW0gCfn0XXAXFlBerRCIPMBv8GB83zTMwZd1WKrfijUZyknwMG0OqZKswPXDn8zLwzT/CEv3DbRiQkN5V7qMaACfoo+FOAdEGsnylfeY/RiaiSpfO+0gJ5FmY2XHKmoMve0TG5c58A0Fc29BjDj/aYtdOgNmqBrZcSJsR3Q1mccertFxJSASdLn2HOpnspRboykNt7A5sRouMUjpkUVhi+k9plH690vrS1clnL3nPWuR8NUI9DD+KZ/lm+IutlPWE=
