language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: "3.7"
    - python: "3.8-dev"
    - python: "nightly"
  fast_finish: true
# install dependencies
install:
  - pip install -U pip
  - pip install -e .[test]
before_script:
# command to run tests
script:
  - make test
  # see the cli installed correctly
  - make example -j3 yaml2cli=yaml2cli -B
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls; else printf "skip coveralls"; fi
before_deploy:
  # - pip install -U twine
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  distributions: "sdist bdist_wheel"
  server: https://pypi.python.org/pypi
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
env:
  global:
    secure: runx5bfn1XNrEm2pH0IPf2XIhy8uX11XszyZwNoQyUHOXAJVoN8f37NJMXk4TvfUvsDJYgIcLxVvahPglKoO/FNbifQu4DlnlUhbpiy9qMT2uuGlSq5qTIqvlVlxbjzsnw3ZGbpgi8d1j+Rvw9qDYla3hGAP1ZjjIXEanDDiMlK7AASet2XCaqvyXLXr+9pXxHP+oe7dNixvFwJ5JuulRb1f1l/o9lnExu7tYtY175GnJMONQs2bBu4PjWXe37yYY0/wDf6itQFDgkbdKV8Z6DUPwlVVdYiY8/D9HwNOU3KPvP3R7b7RrG9uKTzM6RfzNwqMgM+Vkdy2E5qJqVBGB3hc9mmZZtoqvaNY0RuhUGjypesOhLzKMNngaDoxowcfEo5RzjRoUmV77XItqfKiYp5qJTQfamynbCIggJloAevoBZEYtVW6vXRKT8Brhe/UNgyqtNQ8HfqCwqRV/aaLI+rEee2p1B6nXvGxbxR162LwmFDgKUlOMUMTgEyQ8i2at6qKqwhJ2wgoHBXs9uh6Vqi2QIsjb34RFC02q5l2zGxVD6B5LvHlbRd8T+lUjvv64fnF/T0aFhbDILHiKM/JPa7zfmqMLYuqtuuH2WlrL1ZtUSRxruorMq2L6pI07lbHhFr44TkF0zYLIUxMfnW5sez4vv18hk0qTwjmVRA/1S4=
